#
# embed_resources.cmake
#
# Turns files into byte arrays compiled into the plug-in (bdd_resources.h), so it never depends
# on finding files on disk at run time. Adapted from Graphite's.
#
# Run with:
#   cmake -DOUTPUT=<file.cpp> -DSOURCES_ARG=<a|b> -DPATHS_ARG=</a|/b> -P embed_resources.cmake
# SOURCES_ARG are absolute paths; PATHS_ARG what each is served as, in the same order. Both are
# "|"-separated, because a ";" list doesn't survive being passed on a command line.
#

string(REPLACE "|" ";" SOURCES "${SOURCES_ARG}")
string(REPLACE "|" ";" PATHS "${PATHS_ARG}")

set(source "// Generated by cmake/embed_resources.cmake. Do not edit.\n\n")
string(APPEND source "#include \"bdd_resources.h\"\n\nnamespace bdd::vst3 {\n\nnamespace {\n\n")

list(LENGTH SOURCES count)
list(LENGTH PATHS path_count)
if(NOT count EQUAL path_count)
    message(FATAL_ERROR "SOURCES and PATHS must be the same length")
endif()

set(table "")
set(index 0)
while(index LESS count)
    list(GET SOURCES ${index} file)
    list(GET PATHS ${index} served)

    file(READ "${file}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR byte_count "${hex_length} / 2")

    # Two hex digits per byte, as 0x.. literals, 24 to a line.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REPEAT "0x..," 24 line_pattern)
    string(REGEX REPLACE "(${line_pattern})" "\\1\n    " bytes "${bytes}")

    if(served MATCHES "\\.html$")
        set(mime "text/html")
    elseif(served MATCHES "\\.css$")
        set(mime "text/css")
    elseif(served MATCHES "\\.js$")
        set(mime "text/javascript")
    elseif(served MATCHES "\\.json$")
        set(mime "application/json")
    elseif(served MATCHES "\\.ttf$")
        set(mime "font/ttf")
    else()
        set(mime "application/octet-stream")
    endif()

    string(APPEND source "const unsigned char resource${index}[] = {\n    ${bytes}\n};\n\n")
    string(APPEND table "    { \"${served}\", \"${mime}\", resource${index}, ${byte_count} },\n")
    math(EXPR index "${index} + 1")
endwhile()

string(APPEND source "const EmbeddedResource resources[] = {\n${table}};\n\n} // namespace\n\n")
string(APPEND source "const EmbeddedResource* findResource(std::string_view path) {\n")
string(APPEND source "    for (const auto& resource : resources) {\n")
string(APPEND source "        if (path == resource.path) {\n            return &resource;\n        }\n    }\n")
string(APPEND source "    return nullptr;\n}\n\n")
string(APPEND source "const EmbeddedResource* resourcesBegin() { return resources; }\n")
string(APPEND source "const EmbeddedResource* resourcesEnd() { return resources + sizeof(resources) / sizeof(resources[0]); }\n\n")
string(APPEND source "} // namespace bdd::vst3\n")

# Only touch the output when it changes, so an unchanged UI doesn't force a relink.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
    if(existing STREQUAL source)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${source}")
